<?php
/**
 * @file
 * Code for the CA News feature.
 */
include_once('ca_news.features.inc');

if (variable_get('ca_news_term_display') == 'ca_news_term_display_false') {
  drupal_add_css(drupal_get_path('module', 'ca_news') . '/ca_news_no_taxonomy.css');
} else if (variable_get('ca_news_term_display') == 'ca_news_term_display_node') {
  drupal_add_css(drupal_get_path('module', 'ca_news') . '/ca_news_node_taxonomy.css');
}

/**
 * Implements hook_menu()
 */
function ca_news_menu() {
  $items['admin/config/worx_features/news'] = array(
    'title' => 'News Configuration',
    'description' => 'Override settings for ca_news',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ca_news_settings_form'),
    'access arguments' => array('worx features admin'),
    'file' => 'ca_news.admin.inc',
    'file path' => drupal_get_path('module', 'ca_news'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/config/worx_features/news/general'] = array(
    'title' => 'General Settings',
    'description' => 'Override settings for ca_news',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ca_news_settings_form'),
    'access arguments' => array('worx features admin'),
    'file' => 'ca_news.admin.inc',
    'file path' => drupal_get_path('module', 'ca_news'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  
  return $items;
}

/**
 * implements hook_menu_alter().
 */
function ca_news_menu_alter(&$items) {
  $items['news']['title'] = variable_get('ca_news_menu_title', 'News');
}

/**
 * Implements hook_panels_pre_render().
 */
function ca_news_panels_pre_render($panel, $renderer) {
  foreach ($panel->content as $key => $value) {
    if ($value->subtype == 'ca_news-ca_news_list_1') {
      $panel->title = variable_get('ca_news_panel_title', 'News');
    } elseif ($value->subtype == 'ca_news-ca_news_list_2') {
      $panel->title = variable_get('ca_news_panel_title', 'News');
    } elseif ($value->subtype == 'ca_news-ca_news_list_3') {
      $panel->title = variable_get('ca_news_panel_title', 'News');
    } elseif ($value->subtype == 'ca_news-ca_news_list_4') {
      $panel->title = variable_get('ca_news_panel_title', 'News');
    } elseif ($value->subtype == 'ca_news-ca_news_list_5') {
      $panel->title = variable_get('ca_news_panel_title', 'News');
    }
  }
}

/**
 * Implements hook_views_pre_render().
 */
function ca_news_views_pre_view(&$view, &$display_id, &$args) {
  if ($display_id == 'ca_news_list_1') {
    $view->set_items_per_page(variable_get('ca_news_list_count', 5));
  }
  if ($display_id == 'ca_news_block_1') {
    $view->set_items_per_page(variable_get('ca_news_block_count', 1));
  }
}

/**
 * Implementation of hook_ctools_plugin_directory()
 */
function ca_news_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools') {
    return 'plugins/' . $plugin_type;
  }
}

